create table "public"."answer" (
    "id" bigint generated by default as identity not null,
    "question_id" bigint not null,
    "response" text,
    "updated_at" timestamp without time zone not null
);


alter table "public"."answer" enable row level security;

create table "public"."questionnaire" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp without time zone default now(),
    "question" text not null
);


alter table "public"."questionnaire" enable row level security;

CREATE UNIQUE INDEX answer_pkey ON public.answer USING btree (id);

CREATE UNIQUE INDEX questionnaire_pkey ON public.questionnaire USING btree (id);

alter table "public"."answer" add constraint "answer_pkey" PRIMARY KEY using index "answer_pkey";

alter table "public"."questionnaire" add constraint "questionnaire_pkey" PRIMARY KEY using index "questionnaire_pkey";

alter table "public"."answer" add constraint "public_answer_question_id_fkey" FOREIGN KEY (question_id) REFERENCES questionnaire(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."answer" validate constraint "public_answer_question_id_fkey";

grant delete on table "public"."answer" to "anon";

grant insert on table "public"."answer" to "anon";

grant references on table "public"."answer" to "anon";

grant select on table "public"."answer" to "anon";

grant trigger on table "public"."answer" to "anon";

grant truncate on table "public"."answer" to "anon";

grant update on table "public"."answer" to "anon";

grant delete on table "public"."answer" to "authenticated";

grant insert on table "public"."answer" to "authenticated";

grant references on table "public"."answer" to "authenticated";

grant select on table "public"."answer" to "authenticated";

grant trigger on table "public"."answer" to "authenticated";

grant truncate on table "public"."answer" to "authenticated";

grant update on table "public"."answer" to "authenticated";

grant delete on table "public"."answer" to "service_role";

grant insert on table "public"."answer" to "service_role";

grant references on table "public"."answer" to "service_role";

grant select on table "public"."answer" to "service_role";

grant trigger on table "public"."answer" to "service_role";

grant truncate on table "public"."answer" to "service_role";

grant update on table "public"."answer" to "service_role";

grant delete on table "public"."questionnaire" to "anon";

grant insert on table "public"."questionnaire" to "anon";

grant references on table "public"."questionnaire" to "anon";

grant select on table "public"."questionnaire" to "anon";

grant trigger on table "public"."questionnaire" to "anon";

grant truncate on table "public"."questionnaire" to "anon";

grant update on table "public"."questionnaire" to "anon";

grant delete on table "public"."questionnaire" to "authenticated";

grant insert on table "public"."questionnaire" to "authenticated";

grant references on table "public"."questionnaire" to "authenticated";

grant select on table "public"."questionnaire" to "authenticated";

grant trigger on table "public"."questionnaire" to "authenticated";

grant truncate on table "public"."questionnaire" to "authenticated";

grant update on table "public"."questionnaire" to "authenticated";

grant delete on table "public"."questionnaire" to "service_role";

grant insert on table "public"."questionnaire" to "service_role";

grant references on table "public"."questionnaire" to "service_role";

grant select on table "public"."questionnaire" to "service_role";

grant trigger on table "public"."questionnaire" to "service_role";

grant truncate on table "public"."questionnaire" to "service_role";

grant update on table "public"."questionnaire" to "service_role";


